POST http://localhost:3000/pets
Content-Type: application/json

{
    "userId": "user010",
    "petName": "Max6",
    "gender": "male",
    "species": "Beagle",
    "age": 7,
    "image": ["link5", "link6"],
    "behaviorDescription": "calm and intelligent",
    "vaccinatedComment": "pending",
    "video": ["videoLink5", "videoLink6"]
}

###
GET http://localhost:3000/pets

###
GET http://localhost:3000/pets/random

###
GET http://localhost:3000/pets/66e954669734ca16b7af00b6

###
GET http://localhost:3000/user/user008/pets

###
PUT http://localhost:3000/pets/66e954669734ca16b7af00b6
Content-Type: application/json

{
    "vaccinatedComment": "never"
}

###
DELETE http://localhost:3000/pets/66e954669734ca16b7af00b6